---
title: 4-3. Promise
date: 2023-06-01
---
## Ⅰ. 概念
#### 1. Promise介绍
Promise 是异步编程的一种解决方案，比传统的解决方案 回调函数和事件 更合理和更强大。语法上Promise是一个构造函数，用来封装异步操作并可以获取其成功或失败的结果。

所谓Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。Promise 提供统一的 API，各种异步操作都可以用同样的方法进行处理

#### 2. Promise的特点
- 对象的状态不受外界影响：只有异步操作的结果可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。
    - 三个状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）
- 一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected。只要这两种情况发生，就不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。
- 使用promise可以解决回调地狱。
#### 3. 缺点
- 无法取消Promise，一旦新建它就会立即执行，无法中途取消。
- 如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。
- 当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

#### 4. 使用步骤
Promise对象有三个状态：pending（进行中）、fulfilled（resolved 成功）、rejected（失败）
- 初始化Promise对象时，生成Promise实例，Promise对象为pending状态。
- Promise对象有个回调函数，函数内部执行一些异步操作
- 当执行操作成时，使用resolve将Promise状态改为成功，否则使用reject将Promise状态改为失败。resolve和reject是Promise对象的回调函数的两个参数。
- 当Promise对象状态改为成功或失败时，就会自动调用promise对象的then方法，该方法有两个回调函数，分别对应Promise的两个状态，两个状态各自触发对应的回调函数（需要先声明）。


## Ⅱ. 基本用法
#### 1. 实例化promise对象
Promise对象是一个构造函数，用来生成Promise实例。构造函数接受一个函数作为参数，该函数的两个参数分别是 `resolve` 和 `reject`，他们也是两个函数（JS内置的函数）。Promise实例生成以后，可以用then方法分别指定resolved状态和rejected状态的回调函数。
```js
let a = 10;
const p = new Promise((resolve,reject)=>{
    if(a>10){ //异步操作成功
        let value = "yes"
        resolve(value); //成功后，执行resolve函数，状态改为成功
    }else{ //异步操作失败
        let error = "no"
        reject(error);//失败后，执行reject函数，状态改为失败
    }
})
```

- resolve函数：将promise对象的状态从“未完成”变为“成功”（即从 pending 变为 resolved），异步执行成功时使用，并将异步操作的结果，作为参数传递出去。
- reject函数：将Promise对象的状态从“未完成”变为“失败”（即从 pending 变为 rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。
- 注意：调用resolve或reject并不会终结 Promise 的参数函数的执行。有时需要在这两个方法前面加上return，防止出现意外

#### 2. then方法
Promise实例生成以后，可以用then方法分别指定resolved状态和rejected状态的回调函数。
- 参数1：promise对象状态变成resolved时的回调，形参一般设为value
- 参数2：promise对象状态变成rejected时的回调，形参一般设为error
两个函数都是可选的。两个回调接受的参数都是promise对象传出的值。
```js
let p = new Promise(...).then((value)=>{
    console.log(value)//打印的是resolve传递过来的参数
},(error)=>{
    console.log(error)//打印的是reject传递过来的参数
})
```
promise对象创建时，里面的代码会立即执行，then方法指定的回调函数将在当前脚本所有同步任务执行完才会执行。


#### 3. 实例：Promise封装读取文件
**不使用Promise**
```js
import fs from "fs" //fs是nodejS的一个读取文件的模块
//调用fs的方法读取文件
fs.readFile('./a.txt',(err,data)=>{
    if(err){
        throw err;
    }
    console.log(data.toString());
})
```

**使用promise封装**
```js
import fs from "fs" 
const p = new Promise((resolve,reject)=>{
    fs.readFile("./a.txt",(err.data)=>{
        if(err){
            reject(err);
        }
        resolve(data);
    })
}).then((value)=>{
    console.log(value.toString());
},(error)=>{
    console.log("读取失败")
})
```

#### 4. 实例：Promise异步加载图片
```js
function loadImageAsync(url){
    return new Promise((resolve,reject)=>{
        const image = new Image();
        image.onload = function(){
            resolve(image);
        };

        image.onerror = function(){
            reject(new Error("无法加载图片"+ url));
        }

        image.src = url;
    })
}
```


#### 5. 实例：Promise封装Ajax请求
**原生Ajax请求**
```js
const xhr = new XMLHttpRequest();
xhr.open("GET",'https://api.sgugo.com/gettest');
xhr.send();
xhr.onreadystatechange = function(){
    if(xhr.readyState === 4 && xhr.status>=200 &&xhr.status<300){
        console.log(xhr.response);//成功
    }else{
        console.log(xhr.status);//失败
    }
}
```

**使用promise封装**

请求结束后，在then方法中做进一步的处理，而不是直接在回调函数中做处理，代码更加简洁清晰，也不会出现回调地狱的情况。
```js
const p = new Promise((resolve,reject)=>{
    const xhr = new XMLHttpRequest();
    xhr.open("GET",'https://api.sgugo.com/gettest');
    xhr.send();
    xhr.onreadystatechange = function(){
        if(xhr.readyState === 4 && xhr.status>=200 && xhr.status<300){
            return resolve(xhr.response);
        }else{
            return reject(xhr.status);
        }
    }
}).then((value)=>{
    console.log(value);
},(error)=>{
    console.log(error);
})
```

#### 6. Promise的嵌套
resolve函数的参数除了正常的值以外，还可能是另一个 Promise 实例，即一个异步操作的结果是返回另一个异步操作。
```js
const p1 = new Promise((resolve,reject)=>{
    return reject("error-p1");
})

const p2 = new Promise((resolve,reject)=>{
    resolve(p1)
}).then((value)=>{
    console.log("yes-p2: "+value);
},(error)=>{
    console.log("error-p2: "+error);
})
```
注意，p1的状态就会传递给p2，也就是说，p1的状态决定了p2的状态。如果p1的状态是pending，那么p2的回调函数就会等待p1的状态改变；如果p1的状态已经是resolved或者rejected，那么p2的回调函数将会立刻执行。

**执行结果**  
- 先执行p1，此时p1的状态变成了reject。
- 再执行p2，p2的状态是resolved，因此执行resolve函数，该函数执行了p1，由于p1的状态是reject，因此p2的状态也变成了rejected。
- p2执行reject回调，并将p1的参数传入。


## Ⅲ. Promise 的方法
#### 1. Promise.prototype.then()
then的作用是为 Promise 实例添加状态改变时的回调函数。then方法的第一个参数是resolved状态的回调函数，第二个参数是rejected状态的回调函数，它们都是可选的。

promise实例的then方法返回的是一个**新的Promise实例**。因此then方法可以采用链式写法，在then后面继续调用then。第一个then完成后，会将返回结果作为参数，传入第二个then。
```js
const p1 = new Promise((resolve,reject)=>{
    resolve("v1")
}).then((value)=>{
    console.log(value); 
    //return undefined
}, (error)=>{
    console.log(error)
    return new Promise((resolve,reject)=>{
        reject("error")
    })
}).then((value)=>{
    console.log(value+"v3")
},(error)=>{
    console.log(error+"v4")
})
```
p1执行完毕，状态改变（resolve），此时执行第一个：p1.then()，该函数的返回值是一个新的promise，因此可以继续调用then()，无限链接。

第一个then根据p1的状态来执行直接的回调，后续的then会根据前一个then的返回值来决定状态（注意是返回值，不是前一个then的状态），当上一个then没有return（return undefined），默认状态是resolve，如果return了一个Promise对象，且该promise对象是reject，那么状态才会是reject，return其他的值都是resolve状态。如果没有return的话，后续的then就接收不到参数。

#### Promise.prototype.catch()
Promise.prototype.catch()方法是`.then(null, rejection)`或`.then(undefined, rejection)`的别名，用于指定发生错误时的回调函数。跟直接把两个回调写在then是一样的。
另外，then()方法指定的回调函数，如果运行中抛出错误，也会被catch()方法捕获。
```js
promise.then((value)=>{
    //该对象状态变为resolved，则会调用then()方法指定的回调函数
}).catch((error)=>{
    //如果状态变为rejected，就会调用catch()方法指定的回调函数
})
```
- 一般来说，不要在then()方法里面定义 Reject 状态的回调函数（即then的第二个参数），总是使用catch方法。理由是第二种写法可以捕获前面then方法执行中的错误，也更接近同步的写法（try/catch）。
- Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。
- Promise 内部的错误不会影响到 Promise 外部的代码，通俗的说法就是“Promise 会吃掉错误”。
- 如果没有使用catch()方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。

#### 3. Promise.prototype.finally()
finally()方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。

finally方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是fulfilled还是rejected，例如在finally中，关闭访问的服务器资源。
```js
let p = Promise(...);
p.tnen((v)=>{...})
.catch((err)=>{...})
.finally(()=>{...})
```
#### 4. Promise.all()
Promise.all()方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
其实就是将多个异步打包成一个异步。
```js
const p = Promise.all([p1,p2,p3])
 .then(...)
 .catch(...);
```
##### 4.1 参数
该方法一般接收一个数组作为参数，数组的每个值都是一个Promise实例。

也可以不是数组，但要支持Iterator接口，如果值不是Promise实例，会自动转换。
##### 4.2 状态
- resolved：当数组中所有的实例都为resolved时，p的状态才是resolved。此时所有的promise实例的返回值会组成一个数组，传递给回调函数
- rejected：当数组中有一个实例的状态为rejected时，p的状态就会变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。

##### 4.3 不捕获错误
all永远执行成功，不再捕获错误，而是让各自的子实例捕获各自的错误。
```js
const p1 = new Promise((resolve,reject)=>{
    resolve('p1=resolve');
}).then(value=>value).catch(e=>e);

const p2= new Promise((resolve,reject)=>{
    reject('p2=resolve');
}).then(value=>value).catch(e=>e);

Promise.all([p1,p2])
    .then(value=>console.log('ok'))
    .then(e=>cosole.log(e));
//返回结果：["hello", Error: 报错了]
```
上面代码中，p1会resolved，p2首先会rejected，但是p2有自己的catch方法，该方法返回的是一个新的 Promise 实例，p2指向的实际上是这个实例。该实例执行完catch方法后，也会变成resolved，导致Promise.all()方法参数里面的两个实例都会resolved，因此会调用then方法指定的回调函数，而不会调用catch方法指定的回调函数。如果p2没有自己的catch方法，就会调用Promise.all()的catch方法。

#### 5. Promise.resolve()
该方法用来将现有对象转为Promise对象。
```js
let p = Promise.resolve(obj);
```

##### 5.1 情况1 参数是Promise实例
不做任何修改、原封不动地返回这个实例。

##### 5.2 情况2 参数是一个thenable对象
thenable对象指的是具有then方法的对象，比如下面这个对象。Promise.resolve()方法会将这个对象转为 Promise 对象，然后就立即执行thenable对象的then()方法。
```js
let t = {
    then(resolve,reject){
        resolve('ok')
    }
}
```

##### 5.3 情况3 参数是不具有then()方法的对象，或不是对象
如果参数是一个原始值，或者是一个不具有then()方法的对象（即非异步对象），则Promise.resolve()方法返回一个新的 Promise 对象，状态为resolved。
```js
let p = Promise.resolve('hello')
p.then((v)=>{
    console.log(v) //hello
})
```
##### 5.4 情况4 不带有参数
直接返回一个resolved状态的 Promise 对象。如果希望得到一个 Promise 对象，比较方便的方法就是直接调用Promise.resolve()方法。
```js
let p = Promise.resolve();

setTimeout(function () {
  console.log('three'); //第三个输出；在下一轮“事件循环”开始时执行
}, 0);

Promise.resolve().then(function () {
  console.log('two'); //第二个输出；在本轮"事件循环"结束时执行
});

console.log('one'); //第一个输出，立即执行，最先输出
```
#### 6. Promise.reject()
同上，也会返回一个新的 Promise 实例，只是该实例的状态为rejected。
```js
let p = Promise.reject('error');
p.then(null,(e)=>{
    console.log(e);
})
```