---
title: 4-4. async
date: 2023-06-02
---
## Ⅰ. 基础
#### 1. 含义
async 本质上是 Generator 函数的语法糖，使得异步操作更加方便。async函数就是将Generator函数的星号（*）替换成async，yield替换成await而已。

async相比于Generator的改进为：
- 内置执行器
    - 像普通函数一样直接执行，不用调用next，或借用co模块。
    - 内部所有的await会依次执行的。
- 更好的语义
- 更广的适用性：co模块约定，yield命令后面只能是 Thunk 函数或 Promise 对象，而async函数的await命令后面，可以是 Promise 对象和原始类型的值
- 返回值是Promise：async函数完全可以看作多个异步操作，包装成的一个 Promise 对象，而await命令就是内部then命令的语法糖。

#### 2. 声明
函数前面加async，就可以将函数变为async函数，函数状态由return决定。
```js
async function f1(id){
    let uname = await getUserName(id);
    let age = await getUserAge(id);
    return uanme;
}
```

#### 3. 基本示例
指定多少毫秒后输出一个值
```js
async function timeout(ms) {
  await new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function asyncPrint(value, ms) {
  await timeout(ms);
  console.log(value);
}

asyncPrint('hello world', 50);
```
上面代码指定 50 毫秒以后，输出hello world。

#### 4. async函数的多种使用形式
```js
//1.函数声明
async function f1(){...}

//2.函数表达式
const f2 = async function(){...}

//3. class的方法
class C{
    async f3(){
        ...
    }
}

//5.箭头函数
const f4 = async ()=>{...}
```

## Ⅱ. 使用async

#### 1. 返回Promise对象
async函数返回一个 Promise 对象。async函数内部return语句返回的值，会成为then方法回调函数的参数。
```js
async function f(){
    return "hi"
}
f().then((v)=>{
    console.log(v);//hi
})
```

async函数内部抛出错误，会导致返回的 Promise 对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到。
```js
async function f(){
    throw new Error("wrong");
}

f().then((v)=>{
    console.log(v);
},(e)=>{
    console.log(e); //wrong
})
```

#### 2. Promise对象状态变化
async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误。

也就是说，只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数（除非reject了）。
```js
async function getTitle(url) {
  let response = await fetch(url); //操作1：抓取网页
  let html = await response.text(); //操作2：取出文本
  return html.match(/<title>([\s\S]+)<\/title>/i)[1]; //操作3：匹配标题
}

getTitle('https://tc39.github.io/ecma262/')
.then((v)=>{
    console.log(v)
})
```
上面代码中，函数getTitle内部有三个操作，只有这三个操作全部完成，才会执行then方法里面的console.log。

#### 3. await 命令
await必须写在async函数中

正常情况下，await命令后面是一个 Promise 对象，返回该对象的结果（promise成功的值）。如果不是 Promise 对象，就直接返回对应的值。
```js
async function f(){
    return 1;
    // await命令的参数是数值1，这时等同于return 1。
    return await 1;
}

f().then((v)=>{
    consoel.log(v); //1
})
```
##### 3.1 thenable
另一种情况是，await命令后面是一个thenable对象（即定义了then方法的对象），那么await会将其等同于 Promise 对象。

##### 3.2 rejecct
await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被catch方法的回调函数接收到（async的状态变成了reject）。
```js
async function f(){
    await Promise.reject("wrong");
}

f().then((v)=>{
    console.log(v);
}).catch((e)=>{
    console.log(e);//wrong
})
```
上面代码中，await语句前面没有return，但是reject方法的参数依然传入了catch方法的回调函数。这里如果在await前面加上return，效果是一样的。

任何一个await语句后面的 Promise 对象变为reject状态，那么整个async函数都会中断执行。
```js
async function f() {
  await Promise.reject('出错了');
  await Promise.resolve('hello world'); // 不会执行
}
```
##### 3.3 解决中断
可以将第一个await放在try...catch结构里面，这样不管这个异步操作是否成功，第二个await都会执行。
```js
async function f() {
  try {
    await Promise.reject('出错了');
  } catch(e) {
  }
  return await Promise.resolve('hello world');
}

f()
.then(v => console.log(v))// hello world
```
也可以在await后面的 Promise 加一个catch方法，处理前面可能出现的错误
```js
async function f(){
    await Promise.reject("出错了").catch((e)=>{consoel.log(e)});
    return await Promise.resolve("hello")
}
f().then((v)=>{
    console.log(v);
})
```

#### 4. 错误处理
如果await后面的异步操作出错，那么等同于async函数返回的 Promise 对象被reject。
```js
async function f(){
    await new Promise((resolve,reject)=>{
        throw new Error('出错了')
    })
}

f().then(
    v => console.log(v)
)
.catch(
    e => console.log(e) // Error：出错了
)
```

同样，可以通过tyr...catch，或内部添加catch捕获错误。
```js
//示例：使用try...catch结构，实现多次尝试断网连接
const superagent = require('superagent');
let time = 10; //重复10次
async function line(){
    let i;
    for(i=0;i<time;i++){
        try{
            await superagent.get('https://google.com/');
            break; //连上就退出循环
        }catch(e){
            console.log("尝试第"+i+"次连接");
        }
    }
}
```
上面代码中，如果await操作成功，就会使用break语句退出循环；如果失败，会被catch语句捕捉，然后进入下一轮循环。

#### 5. 注意事项
##### 5.1 异常处理
await命令后面的Promise对象，运行结果可能是rejected，最好把await命令放在try...catch代码块中，或者内接catch进行异常处理。
```js
async function f(){
    try{
        await f1();
    }catch(e){
        console.log(e);
    }
}

async function f(){
    await f1().catch((e)=>{console.log(e)});
}
```
##### 5.2 await 同时触发
多个await命令后面的异步操作，如果不存在继发关系（没有先后顺序，不互相依赖），最好让它们同时触发。这样就会缩短程序的执行时间，不用等第一个await操作完成时，才会执行第二个await。
```js
//继发写法
async function f1(){
    let foo = await getFoo();
    let bar = await getBar();
}

//同时触发：写法一
async function f2(){
    let [foo,bar] = await Promise.all([getFoo(),getBar()])
}

//同时触发：写法二
async function f3(){
    //提前执行两个函数
    let fo = getFoo();
    let ba = getBar();
    //await两个函数的执行结果
    let foo = await fo;
    let bar = await ba;
}
```
##### 5.3 await只能写在async函数中
await命令只能用在async函数之中，如果用在普通函数，就会报错。

注意：如果将forEach方法的参数改成async函数，使用await还是会出问题，原因是forEach循环中的函数是并发执行的。可以采用for循环解决。
```js
async function f(){
    let ids= [1,2,3]
    for(let i of users){
        await getUser(i);
    }
}
```
如果确实希望多个请求并发执行，可以使用Promise.all方法。

##### 5.4 async 函数可以保留运行堆栈。
普通函数中，函数a内部运行了一个异步任务b()。当b()运行的时候，函数a()不会中断，而是继续执行。等到b()运行结束，可能a()早就运行结束了，b()所在的上下文环境已经消失了。如果b()或c()报错，错误堆栈将不包括a()。

而async函数中，b()运行的时候，a()是暂停执行，上下文环境都保存着。一旦b()或c()报错，错误堆栈将包括a()。

```js
//1.普通函数
const a = () =>{
    b().then(()=>{
        c();
    })
}
//2.async函数
const a = async () => {
  await b();
  c();
};
```
#### 6. 实例
按顺序完成异步操作，比如，依次远程读取一组 URL，然后按照读取的顺序输出结果。
```js
//继发写法：效率比较差
async function logInOrder(urls){
    for(const url of urls){
        const response = await fetch(url);
        consoel.log(await response.text());
    }
}

//并发写法：效率较高
async function logInOrder(urls){
    // 并发读取远程URL
    const textPromises = urls.map(async url => {
        const response = await fetch(url);
        return response.text();
    });

    // 按次序输出
    for (const textPromise of textPromises) {
        console.log(await textPromise);
    }
}
```
虽然map方法的参数是async函数，但它是并发执行的，因为只有async函数内部是继发执行，外部不受影响。后面的for..of循环内部使用了await，因此实现了按顺序输出。

## Ⅲ. 进阶
#### 1. async函数实现原理
就是将 Generator 函数和自动执行器，包装在一个函数里。

#### 2. 与其他异步处理方法的比较 
目前共有三个异步处理方式：async、Promise、Generator。

以一个案例，来比较三个方式：某个 DOM 元素上面，部署了一系列的动画，前一个动画结束，才能开始后一个。如果当中有一个动画出错，就不再往下执行，返回上一个成功执行的动画的返回值。

##### 2.1 Promise写法
```js
function runAnimations(elem,animations){
    // 变量result用来保存上一个动画的返回值
    let retsult = null;

    // 新建一个空的Promise
    let p = Promise.resolve();

    // 使用then方法，添加所有动画
    for(let anim of animations){
        p = p.then((val)=>{
            result = val;
            return anim(elem);
        })
    }

    // 返回一个部署了错误捕捉机制的Promise
    return p.catch((e)=>{
        //忽略错误，继续向后自行
    }).then(()=>{
        return result;
    })
}
```
##### 2.2 Generator
```js
function runAnimations(elem, animations) {
  return spawn(function*() {
    let result = null;
    try {
      for(let anim of animations) {
        result = yield anim(elem);
      }
    } catch(e) {
      /* 忽略错误，继续执行 */
    }
    return result;
  });
}
```

##### 2.3 async写法
```js
async function runAnimations(element,animations){
    let result = null;//全错就返回null
    try{
        for(let anim of animations){
            result = await anim(elem);
        }
    }catch(e){
        //什么都不处理，继续向下执行
    }
    return result;
}
```

##### 2.4 对比
- Promise: 虽然 Promise 的写法比回调函数的写法大大改进，但是一眼看上去，代码完全都是 Promise 的 API（then、catch等等），操作本身的语义反而不容易看出来。
- Generator: 使用 Generator 函数遍历了每个动画，语义比 Promise 写法更清晰，用户定义的操作全部都出现在spawn函数的内部。这个写法的问题在于，必须有一个任务运行器，自动执行 Generator 函数，上面代码的spawn函数就是自动执行器，它返回一个 Promise 对象，而且必须保证yield语句后面的表达式，必须返回一个 Promise。
- Async：Async函数的实现最简洁，最符合语义，几乎没有语义不相关的代码。

